"""Sphinx configuration for the Vita documentation.

The API reference is generated by autodoc from the compiled extension, so
``vita`` must be importable when the docs are built: either install a wheel, or
build the extension in place and run Sphinx from the repository root.
"""

import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_HAS_INPLACE_BUILD = any(
    (_REPO_ROOT / "vita" / f"vita{suffix}").exists()
    for suffix in (".so", ".pyd", ".dylib")
)

if _HAS_INPLACE_BUILD:
    # Prefer an in-place build when there is one, so the docs can be built right
    # after compiling the extension locally.
    sys.path.insert(0, str(_REPO_ROOT))
else:
    # Otherwise `vita` must come from an installed wheel, which is how CI builds
    # the docs. Drop the repository root from sys.path so the source-tree `vita/`
    # package -- which has no compiled module in it -- cannot shadow the
    # installed one. Whether the root lands on sys.path at all depends on how
    # Sphinx was invoked (`python -m sphinx` adds the working directory,
    # `sphinx-build` does not), so normalize it here rather than relying on that.
    _root_aliases = {str(_REPO_ROOT), "", "."}
    sys.path[:] = [p for p in sys.path if p not in _root_aliases and str(Path(p).resolve()) != str(_REPO_ROOT)]

project = "Vita"
copyright = "2025, David Braun"
author = "David Braun"

_version_globals: dict = {}
exec((Path(__file__).parent.parent / "vita" / "version.py").read_text(), _version_globals)
release = _version_globals["__version__"]
version = release

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "myst_parser",
]

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- HTML ---------------------------------------------------------------------

html_theme = "furo"
html_title = f"Vita {release}"
html_theme_options = {
    "source_repository": "https://github.com/DBraun/Vita/",
    "source_branch": "main",
    "source_directory": "docs/",
}

# -- Extensions ---------------------------------------------------------------

myst_enable_extensions = ["colon_fence", "deflist"]
myst_heading_anchors = 3

autodoc_member_order = "bysource"
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "show-inheritance": False,
}

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable", None),
}
